language: nix
script:
- make -C tests/env nix-env PYTHON=python2
- make -C tests/env nix-env PYTHON=python3
- make -C tests/overrides nix-env PYTHON=python2
- make -C tests/overrides nix-env PYTHON=python3
- make -C tests/package nix-env nix-build nix-sdist nix-wheel nix-test
cache:
  directories:
  - /nix
