language: nix
script:
- make -C examples/package nix-env
- make -C examples/package nix-build
- make -C examples/package nix-test
- make -C examples/package nix-acceptance-test
- make -C examples/package nix-sdist
- make -C examples/package nix-wheel
- make -C examples/env nix-env
cache:
  directories:
  - /nix
